# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 psycopg2 PyGithub
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: | 
        flake8 . --exclude='tests/BrokenTestScript.py' --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E999 --max-line-length=127 --count --exit-zero --max-complexity=10 --statistics
    - name: Docker
      run: |
        docker run --rm --name postgresContainer -e POSTGRES_PASSWORD=my_secret_password -d -p 5432:5432 postgres
    - name: Run with working test script
      run: |
        python3 AutoBugTracker.py -tests/WorkingTestScript.py